[users]

[users.klas]
name = "Klas af Geijerstam"
permissions = 1 # Admin

[users.fredrik]
name = "Fredrik Peteri"
permissions = 1 # Admin

[users.emilia]
name = "Emilia Harr"
permissions = 1 # Admin

[users.admin]
name = "Arne Admin"
permissions = 2 # Super user

[users.student1]
name = "Student1 Studentsson"
permissions = 0 # Normal user

[users.student2]
name = "Student2 Studentsson"
permissions = 0 # Normal user

[users.student3]
name = "Student3 Studentsson"
permissions = 0 # Normal user

[users.student4]
name = "Student4 Studentsson"
permissions = 0 # Normal user
