version: "3.9"
services:
    dev-login-provider:
        build: login/dev_login/
        ports:
            - "8000:8000"
        command: ["8000", "https://localhost"]
    dev-user-provider:
        build: user/toml_provider/
        ports:
            - "9000:9000"
        command: ["9000"]
    
    database:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: "1234"
