# Public host of login server
public_host = ""
port = 25674

# SSL Configuration for RusTLS
certificate_file = "/cert.pem"
key_file = "/key.pem"

login_provider = "http://localhost:9000"
user_provider = "http://localhost:8000"

[database]
host = "database"
port = 5432
user = "postgres"
database = "postgres"
password = "1234"
