# Public host of login server
public_host = ""
port = 25674

# SSL Configuration for RusTLS
certificate_file = "res/localhost+2.pem"
key_file = "res/localhost+2-key.pem"

login_provider = "http://localhost:9000"
user_provider = "http://localhost:8000"

[database]
host = ""
port = 5432
user = "tosca_user"
database = "tosca_database"
password = ""
