#!/bin/bash
if [ ! -d res ]; then
    mkdir res
fi
mkcert localhost 127.0.0.1 ::1
mv ./localhost+2.pem res/cert.pem
mv ./localhost+2-key.pem res/key.pem
echo "Genererated key and certificate to res/key.pem res/cert.pem"
