[users.charles_iusto]
first_name = 'Cary'
last_name = 'Torphy'
user_level = 2

[users.darlene_sed]
first_name = 'Albert'
last_name = 'Wilkinson'
user_level = 2

[users.cornell_eligendi]
first_name = 'Jace'
last_name = 'Boyer'
user_level = 2

[users.antonette_eos]
first_name = 'Claudia'
last_name = 'Lueilwitz'
user_level = 2

[users.amir_rem]
first_name = 'Colton'
last_name = 'Effertz'
user_level = 2

[users.pasquale_et]
first_name = 'Retha'
last_name = 'Schneider'
user_level = 2

[users.mayra_et]
first_name = 'Trisha'
last_name = 'Bayer'
user_level = 2

[users.alda_labore]
first_name = 'Eryn'
last_name = 'Larkin'
user_level = 2

[users.rebekah_debitis]
first_name = 'Therese'
last_name = 'Koepp'
user_level = 2

[users.francisco_nisi]
first_name = 'Guillermo'
last_name = 'Rice'
user_level = 2

[users.kurtis_deleniti]
first_name = 'Cassie'
last_name = 'Jones'
user_level = 2

[users.madge_dolores]
first_name = 'Leon'
last_name = 'Christiansen'
user_level = 2

[users.admin]
first_name = 'Teresa'
last_name = 'Howe'
user_level = 0

[users.germaine_culpa]
first_name = 'Lenore'
last_name = 'Brakus'
user_level = 1

[users.alexandra_quisquam]
first_name = 'Bertrand'
last_name = 'Armstrong'
user_level = 2

[users.cierra_rerum]
first_name = 'Linnea'
last_name = 'Hermann'
user_level = 2

[users.hettie_rerum]
first_name = 'Leann'
last_name = 'White'
user_level = 2

[users.xzavier_est]
first_name = 'Rickie'
last_name = 'Hackett'
user_level = 2

[users.spencer_aperiam]
first_name = 'Myrtle'
last_name = 'Torphy'
user_level = 2

[users."quod.luella"]
first_name = 'Frederick'
last_name = 'Heller'
user_level = 2

[users.brennon_fugiat]
first_name = 'Hoyt'
last_name = 'Corwin'
user_level = 2

[users.jeanie_voluptas]
first_name = 'Marcelino'
last_name = 'Casper'
user_level = 2

[users.rickey_sunt]
first_name = 'Sydnee'
last_name = 'Bode'
user_level = 2

[users.lessie_tempora]
first_name = 'Marlon'
last_name = 'Braun'
user_level = 2

[users.celestine_excepturi]
first_name = 'Jesse'
last_name = 'Schulist'
user_level = 2

[users.halle_nisi]
first_name = 'Lavinia'
last_name = 'Dibbert'
user_level = 2

[users.leonard_aliquam]
first_name = 'Brendon'
last_name = 'McGlynn'
user_level = 2

[users.tabitha_ea]
first_name = 'Billie'
last_name = 'Huel'
user_level = 2

[users.kariane_earum]
first_name = 'Felton'
last_name = 'Kuvalis'
user_level = 2

[users.jailyn_dignissimos]
first_name = 'Jessie'
last_name = 'Runte'
user_level = 2

[users.ewald_tempora]
first_name = 'Alex'
last_name = 'Kuhlman'
user_level = 2

[users.arno172]
first_name = 'Norma'
last_name = 'Bashirian'
user_level = 2

[users.fay_ea]
first_name = 'Gia'
last_name = 'Champlin'
user_level = 2

[users.reilly_et]
first_name = 'Orville'
last_name = 'Ziemann'
user_level = 1

[users.bethany_commodi]
first_name = 'Mireille'
last_name = 'Carroll'
user_level = 1

[users.bernice_quia]
first_name = 'Anastasia'
last_name = 'Bartell'
user_level = 2

[users.alyson_maxime]
first_name = 'Marcelino'
last_name = 'Reichert'
user_level = 1

[users.trycia_iste]
first_name = 'Darrin'
last_name = 'Davis'
user_level = 2

[users.clark_blanditiis]
first_name = 'Shemar'
last_name = 'Brakus'
user_level = 2

[users.lavern_sit]
first_name = 'Lowell'
last_name = 'Breitenberg'
user_level = 2

[users.aryanna_at]
first_name = 'Wilfrid'
last_name = 'Wilderman'
user_level = 2

[users.audie_eveniet]
first_name = 'Cara'
last_name = 'Weissnat'
user_level = 2

[users.mathilde_aut]
first_name = 'Manley'
last_name = 'Olson'
user_level = 2

[users.elmo_incidunt]
first_name = 'Maybelle'
last_name = 'Trantow'
user_level = 2

[users.verda_soluta]
first_name = 'Price'
last_name = 'Nicolas'
user_level = 2

[users.joe_ipsam]
first_name = 'Lonny'
last_name = 'Schinner'
user_level = 2

[users.barry_velit]
first_name = 'Fatima'
last_name = 'Gerlach'
user_level = 2

[users.tabitha_fuga]
first_name = 'Orland'
last_name = 'Baumbach'
user_level = 2

[users.chaya_nihil]
first_name = 'Jaiden'
last_name = 'Huels'
user_level = 2

[users.berneice_reiciendis]
first_name = 'Karolann'
last_name = 'Oberbrunner'
user_level = 2

[users.darron_dolorum]
first_name = 'Fatima'
last_name = 'Rau'
user_level = 1

[users.destinee_laboriosam]
first_name = 'Kobe'
last_name = 'Hirthe'
user_level = 2

[users.carmela_autem]
first_name = 'Conrad'
last_name = 'Beatty'
user_level = 2

[users.austyn_natus]
first_name = 'Garret'
last_name = 'Nader'
user_level = 2

[users.kathryn_provident]
first_name = 'Judah'
last_name = 'Roberts'
user_level = 2

[users.icie_quidem]
first_name = 'Hilario'
last_name = 'Towne'
user_level = 2

[users.john_sequi]
first_name = 'Avery'
last_name = 'Nienow'
user_level = 2

[users.calista_est]
first_name = 'Filomena'
last_name = 'Buckridge'
user_level = 2

[users.nikko_dolores]
first_name = 'Amelia'
last_name = 'Harvey'
user_level = 2

[users.dudley_eos]
first_name = 'Monserrate'
last_name = 'Hirthe'
user_level = 2

[users.christian_quis]
first_name = 'Estevan'
last_name = 'Ziemann'
user_level = 2

[users.marilie_soluta]
first_name = 'Yolanda'
last_name = 'Herzog'
user_level = 2

[users.keyon_est]
first_name = 'Genoveva'
last_name = 'Witting'
user_level = 2

[users.emilio_voluptatum]
first_name = 'Margot'
last_name = 'Klein'
user_level = 2

[users.joey_omnis]
first_name = 'Timmothy'
last_name = 'Kuvalis'
user_level = 2

[users.roy_sit]
first_name = 'Ruben'
last_name = 'Flatley'
user_level = 2

[users.joshua_eligendi]
first_name = 'Houston'
last_name = 'Rippin'
user_level = 2

[users.muhammad_labore]
first_name = 'Jaleel'
last_name = 'Reichel'
user_level = 2

[users.diamond_asperiores]
first_name = 'Ramon'
last_name = 'Metz'
user_level = 2

[users.favian_qui]
first_name = 'Alyce'
last_name = 'Hane'
user_level = 2

[users.lilla_quia]
first_name = 'Pat'
last_name = 'Bruen'
user_level = 2

[users.mireille_maiores]
first_name = 'Dorian'
last_name = 'Lemke'
user_level = 2

[users.rossie_culpa]
first_name = 'Dejon'
last_name = 'Wolff'
user_level = 2

[users.maximillian_consectetur]
first_name = 'Dina'
last_name = 'Terry'
user_level = 2

[users.maudie_et]
first_name = 'Piper'
last_name = 'Weissnat'
user_level = 2

[users.leo_hic]
first_name = 'Porter'
last_name = 'Haag'
user_level = 2

[users.jakob_quibusdam]
first_name = 'Rosa'
last_name = 'Medhurst'
user_level = 2

[users.maybell_tenetur]
first_name = 'Kianna'
last_name = 'Sanford'
user_level = 2

[users.elyssa_esse]
first_name = 'Carlotta'
last_name = 'Turner'
user_level = 2

[users.orrin_dolores]
first_name = 'Arden'
last_name = 'Bahringer'
user_level = 2

[users.loy_qui]
first_name = 'Tiana'
last_name = 'Strosin'
user_level = 2

[users.katlynn_aut]
first_name = 'Madisen'
last_name = 'Gusikowski'
user_level = 2

[users.erick_sed]
first_name = 'Anastasia'
last_name = 'Boehm'
user_level = 2

[users.jordane_neque]
first_name = 'Queen'
last_name = 'Kris'
user_level = 2

[users.cierra_velit]
first_name = 'Ophelia'
last_name = 'Bednar'
user_level = 2

[users.blaise_vel]
first_name = 'Ralph'
last_name = 'Spinka'
user_level = 2
[workspaces."Investment Management"]
users = [
    'cierra_velit',
    'kariane_earum',
    'christian_quis',
    'austyn_natus',
    'john_sequi',
    'orrin_dolores',
    'lessie_tempora',
    'katlynn_aut',
    'dudley_eos',
    'mireille_maiores',
    'hettie_rerum',
    'verda_soluta',
    'carmela_autem',
    'katlynn_aut',
    'keyon_est',
    'austyn_natus',
    'kurtis_deleniti',
    'nikko_dolores',
    'spencer_aperiam',
    'erick_sed',
    'jailyn_dignissimos',
    'austyn_natus',
    'arno172',
    'antonette_eos',
    'francisco_nisi',
    'carmela_autem',
    'dudley_eos',
    'diamond_asperiores',
    'madge_dolores',
    'brennon_fugiat',
]

[workspaces.Ranching]
users = [
    'erick_sed',
    'kathryn_provident',
    'madge_dolores',
    'lessie_tempora',
    'tabitha_ea',
    'bernice_quia',
    'celestine_excepturi',
    'diamond_asperiores',
    'cierra_rerum',
    'keyon_est',
    'rickey_sunt',
    'alexandra_quisquam',
    'kurtis_deleniti',
    'blaise_vel',
    'spencer_aperiam',
    'diamond_asperiores',
    'amir_rem',
    'calista_est',
    'favian_qui',
    'blaise_vel',
    'alda_labore',
    'audie_eveniet',
    'blaise_vel',
    'halle_nisi',
    'audie_eveniet',
    'lilla_quia',
    'darlene_sed',
    'orrin_dolores',
    'tabitha_ea',
    'john_sequi',
    'elyssa_esse',
    'emilio_voluptatum',
    'joe_ipsam',
    'alda_labore',
]

[workspaces."Consumer Goods"]
users = [
    'leo_hic',
    'arno172',
    'erick_sed',
    'madge_dolores',
    'joey_omnis',
    'celestine_excepturi',
    'blaise_vel',
    'mireille_maiores',
    'carmela_autem',
    'loy_qui',
    'leo_hic',
    'trycia_iste',
    'jeanie_voluptas',
    'marilie_soluta',
    'john_sequi',
    'tabitha_fuga',
    'lilla_quia',
    'joe_ipsam',
    'berneice_reiciendis',
    'kariane_earum',
    'rickey_sunt',
    'maybell_tenetur',
    'brennon_fugiat',
    'jakob_quibusdam',
]

[workspaces."Commercial Real Estate"]
users = [
    'spencer_aperiam',
    'chaya_nihil',
    'leonard_aliquam',
    'pasquale_et',
    'cierra_velit',
    'audie_eveniet',
    'darlene_sed',
    'rebekah_debitis',
    'arno172',
    'berneice_reiciendis',
    'lavern_sit',
    'cornell_eligendi',
    'spencer_aperiam',
    'orrin_dolores',
    'ewald_tempora',
    'francisco_nisi',
    'halle_nisi',
    'brennon_fugiat',
    'quod.luella',
    'carmela_autem',
    'rossie_culpa',
    'orrin_dolores',
    'jailyn_dignissimos',
    'roy_sit',
    'arno172',
    'diamond_asperiores',
    'mayra_et',
    'quod.luella',
]

[workspaces.Tobacco]
users = [
    'rickey_sunt',
    'mathilde_aut',
    'calista_est',
    'darlene_sed',
]

[workspaces.Wireless]
users = [
    'roy_sit',
    'tabitha_fuga',
    'muhammad_labore',
    'keyon_est',
    'roy_sit',
    'rossie_culpa',
    'muhammad_labore',
]

[workspaces.Farming]
users = [
    'bernice_quia',
    'lilla_quia',
    'alexandra_quisquam',
    'trycia_iste',
    'orrin_dolores',
    'lilla_quia',
    'elmo_incidunt',
    'joey_omnis',
    'diamond_asperiores',
    'emilio_voluptatum',
    'mayra_et',
    'bernice_quia',
]

[workspaces."Facilities Services"]
users = [
    'dudley_eos',
    'rebekah_debitis',
    'darlene_sed',
    'arno172',
    'blaise_vel',
    'kathryn_provident',
    'chaya_nihil',
    'clark_blanditiis',
    'loy_qui',
    'muhammad_labore',
    'icie_quidem',
    'leonard_aliquam',
    'loy_qui',
    'arno172',
    'mireille_maiores',
    'diamond_asperiores',
    'calista_est',
    'ewald_tempora',
    'hettie_rerum',
    'maximillian_consectetur',
    'rickey_sunt',
]

[workspaces.Automotive]
users = [
    'orrin_dolores',
    'brennon_fugiat',
    'francisco_nisi',
    'lavern_sit',
    'bernice_quia',
    'cierra_velit',
    'arno172',
    'mathilde_aut',
    'muhammad_labore',
    'arno172',
    'madge_dolores',
    'lessie_tempora',
    'maybell_tenetur',
    'maybell_tenetur',
    'austyn_natus',
    'tabitha_fuga',
    'quod.luella',
    'favian_qui',
    'amir_rem',
    'madge_dolores',
    'kurtis_deleniti',
    'xzavier_est',
    'hettie_rerum',
    'jailyn_dignissimos',
    'halle_nisi',
    'maudie_et',
    'lilla_quia',
    'destinee_laboriosam',
    'joshua_eligendi',
    'clark_blanditiis',
    'joe_ipsam',
    'rickey_sunt',
    'joey_omnis',
    'carmela_autem',
    'carmela_autem',
    'christian_quis',
    'rebekah_debitis',
    'mayra_et',
    'leo_hic',
    'jeanie_voluptas',
    'halle_nisi',
    'nikko_dolores',
]

[workspaces."Fine Art"]
users = [
    'quod.luella',
    'keyon_est',
    'joe_ipsam',
    'loy_qui',
    'quod.luella',
    'rickey_sunt',
    'clark_blanditiis',
]
