[users.klas]
first_name = "Klas"
last_name = "af Geijerstam"
user_level = 1 # Admin

[users.fredrik]
first_name = "Fredrik"
last_name = "Peteri"
user_level = 1 # Admin

[users.emilia]
first_name = "Emilia"
last_name = "Harr"
user_level = 1 # Admin

[users.kuba]
first_name = "Jakub"
last_name = "Jagiello"
user_level = 1

[users.admin]
first_name = "Arne"
last_name = "Admin"
user_level = 2 # Super user

[users.student1]
first_name = "Student1"
last_name = "Studentsson"
user_level = 0 # Normal user

[users.student2]
first_name = "Student2"
last_name = "Studentsson"
user_level = 0 # Normal user

[users.student3]
first_name = "Student3"
last_name = "Studentsson"
user_level = 0 # Normal user

[users.student4]
first_name = "Student4"
last_name = "Studentsson"
user_level = 0 # Normal user

[workspaces.5DV202]
users = [
    "student1",
    "student2",
    "student3",
]

[workspaces.5DV201]
users = [
    "student1",
    "student4",
]
