[users.super_user]
first_name = "Super"
last_name = "User"
user_level = 0 # Super User

[users.admin]
first_name = "Admin"
last_name = "User"
user_level = 1 # Admin

[users.normal]
first_name = "Normal"
last_name = "User"
user_level = 2 # Normal

[users.student1]
first_name = "Student1"
last_name = "Studentsson"
user_level = 2 # Normal user

[users.student2]
first_name = "Student2"
last_name = "Studentsson"
user_level = 2 # Normal user

[users.student3]
first_name = "Student3"
last_name = "Studentsson"
user_level = 2 # Normal user

[users.student4]
first_name = "Student4"
last_name = "Studentsson"
user_level = 2 # Normal user

[workspaces.5DV202]
users = [
    "student1",
    "student2",
    "student3",
]

[workspaces.5DV201]
users = [
    "student1",
    "student4",
]
