version: "3.9"
services:
    swagger:
        image: "swaggerapi/swagger-ui"
        ports:
            - "8080:8080"
        environment:
            SWAGGER_JSON: "/app/api.yaml"
        volumes:
            - ".:/app"


